services:
  db:
    image: postgres:16-alpine
    container_name: keychat-db
    environment:
      POSTGRES_DB: key_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keychat-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://db:5432/key_chat
      DB_USER: postgres
      DB_PASS: 1
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend/key-chat
      dockerfile: Dockerfile
    container_name: keychat-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      REACT_APP_API_URL: http://localhost:8080

volumes:
  pgdata:
